# Generated by Django 5.0.1 on 2024-02-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sending',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='sending',
            name='tag',
            field=models.CharField(blank=True, max_length=15, verbose_name='Тег'),
        ),
    ]
