# Generated by Django 5.0.1 on 2024-02-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_alter_sending_options_alter_sending_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
