# Generated by Django 5.0.1 on 2024-02-06 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0003_alter_client_options_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='send.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='send.sending', verbose_name='Рассылка'),
        ),
    ]
